# Generated by Django 5.0.6 on 2024-06-23 04:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('colors', models.JSONField(blank=True, null=True)),
                ('main_colors', models.JSONField(blank=True, null=True)),
                ('user_identifier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='img_blocks.imagemodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
