# Generated by Django 5.0.6 on 2024-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0003_imageschemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='main_image',
            field=models.ImageField(default=1, upload_to='main_images/'),
            preserve_default=False,
        ),
    ]
