# Generated by Django 5.0.6 on 2024-07-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0004_imagemodel_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='color_image',
            field=models.ImageField(default=1, upload_to='color_images/'),
            preserve_default=False,
        ),
    ]
