# Generated by Django 5.0.7 on 2024-07-15 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0006_saveaspdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveaspdf',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
